# Site settings
title: Andre Goersch Portfolio
tagline: User Experience and Interface Designer
#url: "http://andregoersch.com" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /img/social.jpg # be sure to change this image
facebook: fbusername
twitter: twusername
github: ghusername
googleplus: gusername
instagram: igusername

# Contact
phone: "559-301-5890" # This is my real number. You should text me.
email: "andre.goersch@gmail.com" # This is my real email address. Please don't email me.

# Use this for production
#sass:
#    style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.js
